name: Tests
'on':
  push:
    branches:
      - maintenance/0.2.18
  pull_request:
    branches:
      - maintenance/0.2.18
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install poppler-utils
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .[docs,tests]
      - name: Show python dependencies
        run: |
          pip freeze
      - name: Run tests
        run: |
          ./run-tests.sh
      - name: Build package
        if: ${{ success() }}
        run: |
          python setup.py sdist bdist_wheel
